plugin: community.general.proxmox
validate_certs: false
user: "{{ lookup('ansible.builtin.env','PM_USER') }}"
pass: "{{ lookup('ansile.builtin.env', 'PM_PASS') }}"
url: "{{ lookup('ansible.builtin.env', 'TF_VAR_PM_ENDPOINT') }}"
want_facts: true
keyed_groups:
    # proxmox_tags_parsed is an example of a fact only returned when 'want_facts=true'
  - key: proxmox_tags_parsed
    separator: ""
    prefix: group
groups:
  k3s_cluster: "'k3s_cluster' in (proxmox_tags_parsed|list)"
  master: "'master' in (proxmox_tags_parsed|list)"
  node: "'node' in (proxmox_tags_parsed|list)"
compose:
  ansible_host: proxmox_ipconfig0.ip
# Note that this can easily give you wrong values as ansible_host. See further below for
# an example where this is set to `false` and where ansible_host is set with `compose`.
want_proxmox_nodes_ansible_host: false
