- name: Install dependencies
  ansible.builtin.package:
    name:
      - gcc
      - python3-dev
      - python3-setuptools
      - python3-pip
    state: present

- name: Install python3 netaddr
  ansible.builtin.pip:
    name: netaddr
    executable: pip3

- name: Install python3 passlib
  ansible.builtin.pip:
    name: passlib
    executable: pip3
